### ISSUE TITLE
Hello World Query includes 'GeneralSettings.url' which is not valid

### ISSUE THREAD

**Issue by salcode** [wp-graphql/playground.wpgraphql.com#4]
This is a super cool tool for getting acquainted with WPGraphQL.

One note, the first query **Hello World** includes `GeneralSettings.url`, which is not valid and results in the message

> Cannot query field \"url\" on type \"GeneralSettings\".

![screen shot 2019-02-28 at 09 28 56](https://user-images.githubusercontent.com/5194588/53573416-68de0200-3b3b-11e9-8717-a0a7c7ac5713.png)

## Steps to Recreate

1. Go to https://playground.wpgraphql.com/
2. Run the query that is prepopulated on page load

**Comment by jasonbahl** [comment]
closed by #5

**Comment by jasonbahl** [comment]
> This is a super cool tool for getting acquainted with WPGraphQL.
@salcode have you checked out the new docs over at https://docs.wpgraphql.com as well?

There are a lot of examples embedded in there as well. 😄 

> One note, the first query **Hello World** includes `GeneralSettings.url`, which is not valid and results in the message

I _think_ this is because something on the `api.wpgraphql.com` server actually needs to be updated. I can't recall. Either way, no reason to have a broken query in the playground. Thanks for submitting the issue (and corresponding PR!)

**Comment by salcode** [comment]
> have you checked out the new docs over at https://docs.wpgraphql.com as well?
>
> There are a lot of examples embedded in there as well. 😄

Those docs are awesome. It is a ton of great information and I love the live embeds. 💯
